# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 7.3
  - 7.4

os: linux
dist: xenial
group: edge

services:
  - docker

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3f2dee1a025739ac5da7
    on_success: change
    on_failure: always
    on_start: never

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

before_install:
 - nvm install v14.15.0
 - sudo gem install sass -v 3.4.25
 - chmod +x ./scripts/*.sh
 - cp BuildConfig.json.example BuildConfig.json

# prepare travis ci for the build process
install:
 - npm run deploy

# linters
before_script:
 - cp $TRAVIS_BUILD_DIR/travis-ci/Config.php $TRAVIS_BUILD_DIR/src/Include/Config.php
 - cp $TRAVIS_BUILD_DIR/travis-ci/cypress.json $TRAVIS_BUILD_DIR/cypress.json
 - docker-compose -f docker/docker-compose.test.yaml up -d

# execute tests
script:
 - npm test

before_deploy:
 - npm run package

deploy:
  provider: script
  script: npm run demosite
  on:
    all_branches: true
    php: 7.3
    condition: "$TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH = 'develop'"
