name: Test

on:
  push:
    branches:
  pull_request:
    branches:

env:
  node_version: 14

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.3', '7.4']
    name: PHP ${{ matrix.php }} Build & Test
    steps:
    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}
    - uses: actions/checkout@v2.3.2
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.node_version }}
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'

    - name: Check Versions
      run: |
        php --version
        docker --version
        node --version
        npm --version

    - name: Declare some variables
      id: vars
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Build App ${{ matrix.php }}
      run: npm run deploy

    - name: Setup Docker
      run: |
        docker-compose -f docker/docker-compose.test-apache.yaml up -d

    - name: E2E Tests
      run: npm run test

  deploy:
    name: deploy to demo site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dcoker
        run: docker --version
