name: Test

on:
  push:
    branches:
  pull_request:
    branches:

env:
  node_version: 14
  php_version: 7.4

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ env.php_version }} Build & Package
    steps:

    - name: Setup PHP ${{ env.php_version }}
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ env.php_version }}

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.node_version }}
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'

    - name: Checkout ChurchCRM Code
      uses: actions/checkout@v2.3.2
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0

    - name: get-npm-version
      uses: martinbeentjes/npm-get-version-action@master
      id: package-version

    - name: Build ${{ steps.package-version.outputs.current-version}} on ${{ env.php_version }}
      run: npm run deploy

    - name: Package files
      run: npm run package

    - name: Upload Zip file
      uses: actions/upload-artifact@v2
      with:
        name: ChurchCRM-${{steps.package-version.outputs.current-version}}-${{ env.php_version }}.zip
        path: target/ChurchCRM-${{steps.package-version.outputs.current-version}}.zip

    - name: Upload Tar file
      uses: actions/upload-artifact@v2
      with:
        name: ChurchCRM-${{steps.package-version.outputs.current-version}}-${{ env.php_version }}.tar.gz
        path: target/ChurchCRM-${{steps.package-version.outputs.current-version}}.tar.gz

    - name: Setup Var for Next jobs
      id: version_step
      run: echo "::set-output name=version_number::${{steps.package-version.outputs.current-version}}"

  heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ChurchCRM-${{needs.build.outputs.version_number}}-${{ env.php_version }}.tar.gz

      - name: Unzip
        run: tar -xvf ChurchCRM-${{needs.build.outputs.version_number}}-${{ env.php_version }}.tar.gz

      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ChurchCRM CI"
          heroku_email: "george@dawouds.com"
          appdir: churchcrm


  e2e:
    name: Run e2d Tests
    needs: heroku
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.node_version }}
          # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
          registry-url: 'https://registry.npmjs.org'
      - name: install cypress
        run: npm install cypress --save-dev


  docker:
    name: Deploy to demo site
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Nothing yet here"
