name: Test

on:
  push:
    branches:
  pull_request:
    branches:

env:
  node_version: 14

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '7.3']
    name: PHP ${{ matrix.php }} Build & Test
    steps:

    - name: Setup PHP ${{ matrix.php }}
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.node_version }}
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'

    - name: Checkout ChurchCRM Cdoe
      uses: actions/checkout@v2.3.2
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0

    - name: get-npm-version
      uses: martinbeentjes/npm-get-version-action@master
      id: package-version

    - name: Build ${{ steps.package-version.outputs.current-version}} on ${{ matrix.php }}
      run: npm run deploy

    - name: Setup Docker Server
      run: |
        cp test/Docker-Config.php src/Include/Config.php
        docker-compose -f docker/docker-compose-apache-${{ matrix.php }}.yaml up -d

    - name: Package files
      run: npm run package

    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: target/ChurchCRM-${{steps.package-version.outputs.current-version}}.zip

    - name: Setup Cypress and run Tests
      run: |
        wget http://localhost/
        wget http://localhost/api/public/echo
        cp test/Docker-cypress.json cypress.json
        npm run test



  deploy:
    name: deploy to demo site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dcoker
        run: docker --version
